[package]
name = "device_mapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"

[lib]
name = "device_mapper"
path = "src/lib.rs"


[[bin]]
name = "md"
path = "src/main.rs"
